name: wakey
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tm.png
    - assets/images/logo.png
